services:
  - type: worker
    name: telegram-protection-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
        description: "Your Telegram Bot Token from @BotFather"
      - key: OWNER_ID
        sync: false
        description: "Your Telegram User ID from @userinfobot"
      - key: DATABASE_URL
        fromDatabase:
          name: bot_database
          property: connectionString
        description: "Database connection string (auto-provided)"
